// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeOkjEsCb7DDHxsNoYZrjQrExyuGzA3Ls',
    appId: '1:986249206652:web:ec0a03e9ce831f4889a2f9',
    messagingSenderId: '986249206652',
    projectId: 'dhkin-mobiles',
    authDomain: 'dhkin-mobiles.firebaseapp.com',
    storageBucket: 'dhkin-mobiles.firebasestorage.app',
    measurementId: 'G-X95CFB14ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH3WW2cQnTeqQBLjevIIGPOp952yd52cw',
    appId: '1:986249206652:android:061f58c49f51964189a2f9',
    messagingSenderId: '986249206652',
    projectId: 'dhkin-mobiles',
    storageBucket: 'dhkin-mobiles.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT5-ExbKZCzXruae2rn-Th8cr3iZxf8UE',
    appId: '1:986249206652:ios:4de21cabedbdff1a89a2f9',
    messagingSenderId: '986249206652',
    projectId: 'dhkin-mobiles',
    storageBucket: 'dhkin-mobiles.firebasestorage.app',
    iosBundleId: 'com.dhkin.mobiles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT5-ExbKZCzXruae2rn-Th8cr3iZxf8UE',
    appId: '1:986249206652:ios:4de21cabedbdff1a89a2f9',
    messagingSenderId: '986249206652',
    projectId: 'dhkin-mobiles',
    storageBucket: 'dhkin-mobiles.firebasestorage.app',
    iosBundleId: 'com.dhkin.mobiles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeOkjEsCb7DDHxsNoYZrjQrExyuGzA3Ls',
    appId: '1:986249206652:web:08af5ff904784ed189a2f9',
    messagingSenderId: '986249206652',
    projectId: 'dhkin-mobiles',
    authDomain: 'dhkin-mobiles.firebaseapp.com',
    storageBucket: 'dhkin-mobiles.firebasestorage.app',
    measurementId: 'G-0NP6WXYR7E',
  );
}
